"""
Django settings for sch17 project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os
from . import secretkey

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = secretkey.secretkey
DEBUG = True
ALLOWED_HOSTS = []
INSTALLED_APPS = ['djangocms_admin_style', 'django.contrib.admin',
                  'django.contrib.auth', 'django.contrib.contenttypes',
                  'django.contrib.sessions', 'django.contrib.messages',
                  'django.contrib.staticfiles', 'django.contrib.sites', 'cms', 'menus',
                  'treebeard', 'sekizai', 'filer', 'easy_thumbnails', 'mptt',
                  'djangocms_text_ckeditor', 'djangocms_link', 'djangocms_file',
                  'djangocms_picture', 'djangocms_video', 'djangocms_googlemap',
                  'djangocms_snippet', 'djangocms_style', 'aldryn_apphooks_config',
                  'parler', 'taggit', 'taggit_autosuggest', 'meta', 'djangocms_blog',
                  'sortedm2m']
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware',
              'django.contrib.sessions.middleware.SessionMiddleware',
              'django.middleware.common.CommonMiddleware',
              'django.middleware.csrf.CsrfViewMiddleware',
              'django.contrib.auth.middleware.AuthenticationMiddleware',
              'django.contrib.messages.middleware.MessageMiddleware',
              'django.middleware.clickjacking.XFrameOptionsMiddleware',
              'cms.middleware.user.CurrentUserMiddleware',
              'cms.middleware.page.CurrentPageMiddleware',
              'cms.middleware.toolbar.ToolbarMiddleware',
              'cms.middleware.language.LanguageCookieMiddleware',
              'cms.middleware.utils.ApphookReloadMiddleware']
ROOT_URLCONF = 'sch17.urls'
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates',
              'DIRS': [os.path.join(BASE_DIR, 'templates')], 'APP_DIRS': True,
              'OPTIONS': {'context_processors': [
                  'django.template.context_processors.debug',
                  'django.template.context_processors.request',
                  'django.contrib.auth.context_processors.auth',
                  'django.contrib.messages.context_processors.messages',
                  'sekizai.context_processors.sekizai',
                  'cms.context_processors.cms_settings',
                  'django.template.context_processors.i18n']}}]
WSGI_APPLICATION = 'sch17.wsgi.application'
DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME':
    BASE_DIR / 'db.sqlite3'}}
AUTH_PASSWORD_VALIDATORS = [{'NAME':
                                 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
                             }, {'NAME':
                                     'django.contrib.auth.password_validation.MinimumLengthValidator'}, {
                                'NAME':
                                    'django.contrib.auth.password_validation.CommonPasswordValidator'}, {
                                'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}
                            ]
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'sch17/static'),]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID = 1
LANGUAGES = [('en', 'English'), ('ru', 'Russian')]
X_FRAME_OPTIONS = 'SAMEORIGIN'
CMS_TEMPLATES = [('base-cms.html', 'Base CMS template')]
THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PROCESSORS = ('easy_thumbnails.processors.colorspace',
                        'easy_thumbnails.processors.autocrop',
                        'filer.thumbnail_processors.scale_and_crop_with_subject_location',
                        'easy_thumbnails.processors.filters')
META_SITE_PROTOCOL = 'https'
META_USE_SITES = True
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_USE_SCHEMAORG_PROPERTIES = True

